/**/controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    lift_controller:
      type: joint_hardware/LiftController

/**/joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false
